# Generated by Django 5.1.1 on 2024-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
